name: build
on:
  workflow_dispatch:

env:
  container_name: myimage

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - linux/arm64
          - linux/amd64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare buildah
        run: |-
          sudo apt-get update
          sudo apt-get install buildah qemu-user-static podman -y
          buildah -v
      - name: Build and export container image
        run: |-
          # build image
          export container_name_with_arch="${container_name}-$(echo ${{ matrix.arch }} | sed -e "s/\//-/g" )"
          echo "target container name: $container_name_with_arch"
          echo
          buildah bud -t $container_name_with_arch --platform ${{ matrix.arch }} .
          # export image
          mkdir -p target/images
          buildah push $container_name_with_arch docker-archive:target/images/$container_name_with_arch.tar
          echo
          tree -h
      - uses: actions/upload-artifact@v3
        name: upload artifact
        with:
          name: images
          path: target/images
  
  push-to-registry:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v2
        name: Download artifacts
        with:
          name: images
          path: images
      - name: Listing
        run: |-
          ls -lah
          tree -h
      - name: Create manifest and add image from archs
        run: |-
          buildah manifest create $container_name
          for f in $(ls images)
          do
            export arch=$(echo $f | sed -r -e "s/^(.+)-(.+)-(.+)\.tar$/\2\/\3/g")
            buildah manifest add $container_name docker-archive:images/$f --arch $arch
          done
          echo
          echo buildah manifest inspect $container_name
